import type { AppLocale } from "./locale";

const S = {
  unofficial: {
    en: "Unofficial",
    ru: "Неофициально",
    de: "Inoffiziell",
    fr: "Non officiel",
    it: "Non ufficiale",
    es: "No oficial",
  },
  relatedVideos: {
    en: "Related video guides",
    ru: "Связанные видеогайды",
    de: "Verwandte Videoguides",
    fr: "Guides vidéo liés",
    it: "Guide video correlate",
    es: "Guías de vídeo relacionadas",
  },
  viewAllVideos: {
    en: "Video library",
    ru: "Библиотека видео",
    de: "Videobibliothek",
    fr: "Bibliothèque vidéo",
    it: "Libreria video",
    es: "Biblioteca de vídeos",
  },
  viewAllCount: {
    en: "View all videos",
    ru: "Все видео",
    de: "Alle Videos",
    fr: "Toutes les vidéos",
    it: "Tutti i video",
    es: "Todos los vídeos",
  },
  recommended: { en: "Recommended", ru: "Рекомендуется", de: "Empfohlen", fr: "Recommandé", it: "Consigliato", es: "Recomendado" },
  useful: { en: "Useful", ru: "Полезно", de: "Nützlich", fr: "Utile", it: "Utile", es: "Útil" },
  supplementary: { en: "Supplementary", ru: "Дополнительно", de: "Ergänzend", fr: "Complémentaire", it: "Complementare", es: "Complementario" },
  legacy: { en: "Legacy", ru: "Устаревшее", de: "Legacy", fr: "Ancien", it: "Legacy", es: "Antiguo" },
  playOnYoutube: {
    en: "Watch on YouTube",
    ru: "Смотреть на YouTube",
    de: "Auf YouTube ansehen",
    fr: "Voir sur YouTube",
    it: "Guarda su YouTube",
    es: "Ver en YouTube",
  },
  playInline: { en: "Play here", ru: "Смотреть здесь", de: "Hier abspielen", fr: "Lire ici", it: "Riproduci qui", es: "Reproducir aquí" },
  translationMissing: {
    en: "This page is not translated yet. Showing the English documentation.",
    ru: "Русской версии этой страницы пока нет. Показана английская документация.",
    de: "Diese Seite ist noch nicht übersetzt. Es wird die englische Dokumentation angezeigt.",
    fr: "Cette page n’est pas encore traduite. Documentation anglaise affichée.",
    it: "Questa pagina non è ancora tradotta. Viene mostrata la documentazione in inglese.",
    es: "Esta página aún no está traducida. Se muestra la documentación en inglés.",
  },
  translationOutdated: {
    en: "The English documentation has changed since this translation.",
    ru: "Английская документация изменилась после этого перевода.",
    de: "Die englische Dokumentation hat sich seit dieser Übersetzung geändert.",
    fr: "La documentation anglaise a changé depuis cette traduction.",
    it: "La documentazione inglese è cambiata dopo questa traduzione.",
    es: "La documentación en inglés ha cambiado desde esta traducción.",
  },
  viewEnglish: {
    en: "View current English version",
    ru: "Открыть актуальную английскую версию",
    de: "Aktuelle englische Fassung",
    fr: "Version anglaise actuelle",
    it: "Versione inglese attuale",
    es: "Versión inglesa actual",
  },
  translationKicker: { en: "Translation", ru: "Перевод", de: "Übersetzung", fr: "Traduction", it: "Traduzione", es: "Traducción" },
  translationStatus: {
    en: "Translation status",
    ru: "Статус перевода",
    de: "Übersetzungsstatus",
    fr: "État de la traduction",
    it: "Stato della traduzione",
    es: "Estado de la traducción",
  },
  outdated: { en: "Outdated", ru: "Устарел", de: "Veraltet", fr: "Obsolète", it: "Non aggiornato", es: "Desactualizado" },
  searchDocs: {
    en: "Search documentation",
    ru: "Искать в документации",
    de: "Dokumentation durchsuchen",
    fr: "Rechercher dans la documentation",
    it: "Cerca nella documentazione",
    es: "Buscar en la documentación",
  },
  videoSearch: {
    en: "Search videos…",
    ru: "Поиск видео…",
    de: "Videos suchen…",
    fr: "Rechercher des vidéos…",
    it: "Cerca video…",
    es: "Buscar vídeos…",
  },
  allTopics: { en: "All topics", ru: "Все темы", de: "Alle Themen", fr: "Tous les sujets", it: "Tutti gli argomenti", es: "Todos los temas" },
  allQuality: { en: "All quality", ru: "Все уровни", de: "Alle Qualitäten", fr: "Toutes qualités", it: "Tutte le qualità", es: "Todas las calidades" },
  allLanguages: { en: "All languages", ru: "Все языки", de: "Alle Sprachen", fr: "Toutes les langues", it: "Tutte le lingue", es: "Todos los idiomas" },
  englishLabel: { en: "English", ru: "английский", de: "Englisch", fr: "anglais", it: "inglese", es: "inglés" },
  sourceVerified: { en: "Source verified", ru: "Источник проверен", de: "Quelle geprüft", fr: "Source vérifiée", it: "Fonte verificata", es: "Fuente verificada" },
  sourceStatus: { en: "Source status", ru: "Статус источника", de: "Quellenstatus", fr: "État de la source", it: "Stato della fonte", es: "Estado de la fuente" },
  preferVideo: { en: "Prefer video?", ru: "Смотреть видео?", de: "Lieber Video?", fr: "Préférer la vidéo ?", it: "Preferisci il video?", es: "¿Prefieres vídeo?" },
  learnYourWay: { en: "Learn your way", ru: "Как учиться", de: "So lernen", fr: "Votre parcours", it: "Come imparare", es: "Cómo aprender" },
  documentation: { en: "Documentation", ru: "Документация", de: "Dokumentation", fr: "Documentation", it: "Documentazione", es: "Documentación" },
  videoGuides: { en: "Video guides", ru: "Видеогайды", de: "Videoguides", fr: "Guides vidéo", it: "Guide video", es: "Guías de vídeo" },
  apiReference: { en: "API reference", ru: "Справочник API", de: "API-Referenz", fr: "Référence API", it: "Riferimento API", es: "Referencia API" },
  language: { en: "Language", ru: "Язык", de: "Sprache", fr: "Langue", it: "Lingua", es: "Idioma" },
  topic: { en: "Topic", ru: "Тема", de: "Thema", fr: "Sujet", it: "Argomento", es: "Tema" },
  quality: { en: "Quality", ru: "Класс", de: "Qualität", fr: "Qualité", it: "Qualità", es: "Calidad" },
  noVideos: {
    en: "No verified public videos for these filters.",
    ru: "Нет проверенных публичных видео по этим фильтрам.",
    de: "Keine geprüften öffentlichen Videos für diese Filter.",
    fr: "Aucune vidéo publique vérifiée pour ces filtres.",
    it: "Nessun video pubblico verificato per questi filtri.",
    es: "No hay vídeos públicos verificados para estos filtros.",
  },
  hostedOnYoutube: {
    en: "Hosted on YouTube. This site does not download or rehost the files.",
    ru: "Файлы остаются на YouTube. Этот сайт их не скачивает и не зеркалирует.",
    de: "Liegt auf YouTube. Diese Site lädt die Dateien nicht herunter und hostet sie nicht.",
    fr: "Hébergé sur YouTube. Ce site ne télécharge ni ne republie les fichiers.",
    it: "Ospitato su YouTube. Questo sito non scarica né rimette online i file.",
    es: "Alojado en YouTube. Este sitio no descarga ni republica los archivos.",
  },
  originalTitle: {
    en: "Original YouTube title",
    ru: "Оригинальное название на YouTube",
    de: "Originaltitel auf YouTube",
    fr: "Titre YouTube d’origine",
    it: "Titolo originale su YouTube",
    es: "Título original de YouTube",
  },
  whatItCovers: {
    en: "What it covers",
    ru: "О чём ролик",
    de: "Inhalt",
    fr: "Contenu",
    it: "Di cosa tratta",
    es: "Qué cubre",
  },
  partOf: { en: "Part of", ru: "Часть серии", de: "Teil von", fr: "Fait partie de", it: "Parte di", es: "Parte de" },
  pageKicker: { en: "Page", ru: "Страница", de: "Seite", fr: "Page", it: "Pagina", es: "Página" },
  sourceKicker: { en: "Source", ru: "Источник", de: "Quelle", fr: "Source", it: "Fonte", es: "Fuente" },
  verified: { en: "Verified", ru: "Проверено", de: "Geprüft", fr: "Vérifié", it: "Verificato", es: "Verificado" },
  reportIssue: {
    en: "Report an issue",
    ru: "Сообщить о проблеме",
    de: "Problem melden",
    fr: "Signaler un problème",
    it: "Segnala un problema",
    es: "Informar de un problema",
  },
  viewWiki: {
    en: "View original Wiki",
    ru: "Открыть исходную Wiki",
    de: "Original-Wiki",
    fr: "Wiki d’origine",
    it: "Wiki originale",
    es: "Wiki original",
  },
  footerDisclaimer: {
    en: "Unofficial community documentation. Not affiliated with or endorsed by Frictional Games.",
    ru: "Неофициальная документация сообщества. Не связана с Frictional Games и не одобрена ими.",
    de: "Inoffizielle Community-Dokumentation. Nicht von Frictional Games unterstützt.",
    fr: "Documentation communautaire non officielle. Non affiliée à Frictional Games.",
    it: "Documentazione community non ufficiale. Non affiliata a Frictional Games.",
    es: "Documentación comunitaria no oficial. No afiliada a Frictional Games.",
  },
  wikiSources: {
    en: "Wiki sources imported",
    ru: "импортированных страниц Wiki",
    de: "importierte Wiki-Quellen",
    fr: "sources Wiki importées",
    it: "fonti Wiki importate",
    es: "fuentes Wiki importadas",
  },
  apiIndexed: {
    en: "API signatures indexed",
    ru: "проиндексированных сигнатур API",
    de: "indexierte API-Signaturen",
    fr: "signatures API indexées",
    it: "firme API indicizzate",
    es: "firmas API indexadas",
  },
  undocumentedApi: {
    en: "undocumented auto-generated API class pages",
    ru: "автосгенерированных страниц API без описания",
    de: "undokumentierte auto-generierte API-Klassenseiten",
    fr: "pages de classes API auto-générées non documentées",
    it: "pagine API auto-generate senza documentazione",
    es: "páginas de clase API autogeneradas sin documentar",
  },
  wipPages: {
    en: "Wiki pages marked WIP in the manifest",
    ru: "страниц Wiki со статусом WIP в манифесте",
    de: "Wiki-Seiten im Manifest als WIP",
    fr: "pages Wiki marquées WIP dans le manifeste",
    it: "pagine Wiki contrassegnate WIP nel manifesto",
    es: "páginas Wiki marcadas WIP en el manifiesto",
  },
  lastSync: {
    en: "Last source sync",
    ru: "Последняя синхронизация",
    de: "Letzte Quell-Synchronisation",
    fr: "Dernière synchro source",
    it: "Ultima sync sorgente",
    es: "Última sincronización",
  },
  imagesNote: {
    en: "Images not inlined (File: license not confirmed)",
    ru: "Изображения не встроены (лицензия File: не подтверждена)",
    de: "Bilder nicht eingebettet (File:-Lizenz unklar)",
    fr: "Images non intégrées (licence File: non confirmée)",
    it: "Immagini non incorporate (licenza File: non confermata)",
    es: "Imágenes no incrustadas (licencia File: no confirmada)",
  },
  closeEmbed: { en: "Close player", ru: "Закрыть плеер", de: "Player schließen", fr: "Fermer le lecteur", it: "Chiudi il lettore", es: "Cerrar el reproductor" },
  coverageCurrent: { en: "current", ru: "актуально", de: "aktuell", fr: "à jour", it: "aggiornato", es: "al día" },
  coverageMissing: { en: "missing", ru: "нет перевода", de: "fehlt", fr: "absent", it: "mancante", es: "falta" },
  otherLanguage: { en: "Other", ru: "Другой", de: "Andere", fr: "Autre", it: "Altro", es: "Otro" },
  series: { en: "Series", ru: "Серия", de: "Serie", fr: "Série", it: "Serie", es: "Serie" },
  warning: { en: "Warning", ru: "Предупреждение", de: "Hinweis", fr: "Avertissement", it: "Avviso", es: "Aviso" },
} as const;

export type UiKey = keyof typeof S;

export function t(key: UiKey, locale: AppLocale): string {
  const row = S[key];
  return row[locale] || row.en;
}

export function qualityLabel(quality: string, locale: AppLocale): string {
  if (quality === "recommended") return t("recommended", locale);
  if (quality === "useful") return t("useful", locale);
  if (quality === "supplementary") return t("supplementary", locale);
  if (quality === "legacy") return t("legacy", locale);
  return quality;
}
